<article class="bugdoc">
    <h2 class="bugdoc-title" id="Bug-Doc:PE22319">PE22319: B004</h2>
    <h3>B004</h3>
    <section id="tip">
     <h4 style="border-top: 0pt; padding: 0pt 4pt 4pt 4pt;">缺陷信息</h4>
                <dl>
                    <dt>缺陷ID</dt>
                    <dd>PE22319</dd>
                    <dt>标签</dt>
                    <dd>flake8</dd>
                    <dt>目录</dt>
                    <dd>Code style and efficiency</dd>
                    <dt>作者</dt>
                    <dd>pinpoint</dd>
                </dl>
    <h2>缺陷成因</h2>

<pre><code>B004使用`hasattr(x, '__call__')`来测试`x`是否可调用是不可靠的。如果`x`实现自定义的`getattr`或其`uuCall`本身不可调用，则可能会得到误导性的结果。使用`callable（x）`可获得一致的结果。 

</code></pre>
<h4>References</h4>
<section class="footnotes">
<ol>
<li id="fn-1"><p>https://www.python.org/dev/peps/pep-0008/<a href="#fnref-1" class="footnote">&#8617;</a></p></li>
</ol>
</section>

    </section>
</article>
