<article class="bugdoc">
    <h2 class="bugdoc-title" id="Bug-Doc:PE22279">PE22279: S323</h2>
    <h3>S323</h3>
    <section id="tip">
     <h4 style="border-top: 0pt; padding: 0pt 4pt 4pt 4pt;">缺陷信息</h4>
                <dl>
                    <dt>缺陷ID</dt>
                    <dd>PE22279</dd>
                    <dt>标签</dt>
                    <dd>flake8</dd>
                    <dt>目录</dt>
                    <dd>Code style and efficiency</dd>
                    <dt>作者</dt>
                    <dd>pinpoint</dd>
                </dl>
    <h2>缺陷成因</h2>

<pre><code>S323默认情况下，Python将创建一个安全的、经过验证的ssl上下文，以便在HTTPSConnection等类中使用。但是，它仍然允许通过_create_unverified_context使用不安全的上下文，该上下文将还原为以前不验证证书或执行主机名检查的行为。

</code></pre>
<h4>References</h4>
<section class="footnotes">
<ol>
<li id="fn-1"><p>https://www.python.org/dev/peps/pep-0008/<a href="#fnref-1" class="footnote">&#8617;</a></p></li>
</ol>
</section>

    </section>
</article>
